# Site settings
title: Iramar Falcão
description: Iramar Falcão
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Iramar Falcão
user_description: 
user_title: Desenvolvedor Web/Mobile
email: iramar.j@hotmail.com
twitter_username: 
github_username:  iramarJunior
gplus_username:  

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
